# Generated by Django 5.1.4 on 2025-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
