# Generated by Django 5.1.4 on 2025-10-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Service'), ('pay_now', 'Pay Now')], default='cash', max_length=20),
        ),
    ]
